CC=aztec34_cc
CFLAGS=-D__MSDOS__
STRIP=aztec34_sqz
LDFLAGS=-lm -lc
LD=aztec34_link
BINEXT=.com

TOOLS=cmdinfo$(BINEXT) cmdmod$(BINEXT) bin2cmd$(BINEXT) exe2cmd$(BINEXT)

all: $(TOOLS)

include Makefile.emutest

bin2cmd$(BINEXT): bin2cmd.o
	$(LD) -o $@ $< $(LDFLAGS)

cmdinfo$(BINEXT): cmdinfo.o
	$(LD) -o $@ $< $(LDFLAGS)

cmdmod$(BINEXT): cmdmod.o
	$(LD) -o $@ $< $(LDFLAGS)

exe2cmd$(BINEXT): exe2cmd.o
	$(LD) -o $@ $< $(LDFLAGS)

.c.o:
	$(CC) $(CFLAGS) $<
	$(STRIP) $@

clean:
	$(RM) *.o $(TOOLS)
	$(RM) -r emu-test

test: test-emu2

