CC=aztec_cc
CFLAGS=-D__CPM86__ 
STRIP=aztec_sqz
LDFLAGS=-lm -lc86
LD=aztec_link
BINEXT=.cmd

TOOLS=cmdinfo$(BINEXT) bin2cmd$(BINEXT)

all: $(TOOLS)

bin2cmd$(BINEXT): bin2cmd.o
	$(LD) -o $@ $< $(LDFLAGS)

cmdinfo$(BINEXT): cmdinfo.o
	$(LD) -o $@ $< $(LDFLAGS)

.c.o:
	$(CC) $(CFLAGS) $<
	$(STRIP) $@

clean:
	$(RM) *.o $(TOOLS)

